baseurl = "http://rajphys.github.io"
title = "Raj Kumar Manna"
#copyright = "&copy; 2016 Raj Kumar Manna"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[image]
  preview_only = true

[params]
  name = "Raj Kumar Manna"
  role = "Postdoctoral Scholar "
  organization = "University of Pittsburgh"
  avatar = "raj1.jpg"
  email = "rkm36@pitt.edu"
  address = "313 Schenley Place, 4420 Bayard Street, University of Pittsburgh, Pittsburgh, PA 15213"
  office_hours = ""
  phone = "+1 412-648-9250"
  skype = ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  #custom_css = ["green.css"]
  #custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  #[[params.social]]
  #  icon = "envelope"
  #  icon_pack = "fa"
  #  link = "mailto:rkm36@pitt.edu"

  #[[params.social]]
  #  icon = "twitter"
  #  icon_pack = "fa"
  #  link = "//twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.co.in/citations?user=SKm3JGsAAAAJ&hl=en"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Raj_Manna2"

  #[[params.social]]
  #  icon = "github"
  #  icon_pack = "fa"
  #  link = "//github.com/gcushen"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

#[[menu.main]]
#  name = "Publications"
#  url = "#publications"
#  weight = 2


[[menu.main]]
  name = "Publications"
  url = "publication1/"
  weight = 4
#[[menu.main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 2




#[[menu.main]]
#  name = "Research"
#  url = "research/"
#  weight = 5
  
  
  [[menu.main]]
  name = "Research"
  url = "research1/"
  weight = 5

#[[menu.main]]
#  name = "Project"
#  url = "#project"
#  weight = 5

[[menu.main]]
  name = "Contact"
  url = "contact/#contact"
  weight = 6

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
